Tracking Table/SimpleTable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from SimpleTable import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='internals/'), name='home'),
    path('internals/', views.Internals.as_view(), name='internals'),
    path('externals/', views.Externals.as_view(), name='externals'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('table/', include('table.urls', namespace='table')),
    path('internals/react/', views.react_response, name='react'),
]

Tracking Table/table/urls.py
from django.urls import path
from table import views

app_name = 'table'

urlpatterns = [
    path('createOrder/', views.CreateOrder.as_view(), name='newOrder'),
    path('editOrder/<int:pk>/', views.EditOrder.as_view(), name='editOrder'),
    path('deleteOrder/<int:pk>', views.DeleteOrder.as_view(), name='deleteOrder'),
    path('updateOrder/<int:pk>', views.UpdateOrder.as_view(), name='updateOrder'),
    path('printOrder/<int:pk>', views.PrintOrder.as_view(), name='printOrder'),
    path('getOrderHistory/<int:pk>', views.GetOrderHistory.as_view(), name='orderHistory'),
]

Tracking Table/table/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView, TemplateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import JsonResponse
from django.core import serializers

from lib import custom_classes
from accounts.models import User
from table.models import Order, Plate, Edge, Payment, Cutting, Edging, Other, Change 
from table import forms
from SimpleTable.forms import PlateProgressFormSet, EdgeProgressFormSet, UpdateOrderProgressForm
import json

class CreateOrder(LoginRequiredMixin, CreateView):

    form_class = forms.CreateOrderForm
    template_name = 'table/newOrder.html'

    def get_context_data(self, **kwargs):
        context = super(CreateOrder, self).get_context_data(**kwargs)
        context['add_note'] = forms.AddNoteForm

        return context

    def post(self, request):

        form_class = self.get_form_class()
        form = self.get_form(form_class)

        note = self.request.POST['content']
        user = self.request.user

        return self.form_valid(form, note, user)

    def form_valid(self, form, note, user):

        self.object = form.save(commit=False)
        self.object.save()

        Change.objects.create(
            cutID=self.object,
            user=user.first_name, 
            operation='created', 
            what='Order',
            new_state=self.object.ID,
            ).save()

        add_note = forms.AddNoteForm(self.request.POST).save(commit=False)
        add_note.cutID = self.object
        add_note.user = user
        add_note.content = note

        if note != '':
            add_note.save()

            Change.objects.create(
            cutID=self.object,
            user=user.first_name, 
            operation='created', 
            what='Note',
            new_state=note,
            ).save()

        return redirect('table:editOrder', self.object.pk)

class EditOrder(LoginRequiredMixin, UpdateView):

    model = Order
    form_class = forms.UpdateOrderForm
    template_name = 'table/editOrder.html'
    
    def get_context_data(self, **kwargs):

        context = super(EditOrder, self).get_context_data(**kwargs)

        self.object.update()

        if self.request.POST:
            context['plate_forms'] = kwargs['PLATES']
            context['cutting_forms'] = kwargs['CUTTING']
            context['edge_forms'] = kwargs['EDGES']
            context['edging_forms'] = kwargs['EDGING']
            context['others_forms'] = kwargs['OTHER']
            context['payment_forms'] = kwargs['PAYMENTS']
            context['add_note'] = kwargs['add_note']
        else:
            context['plate_forms'] = forms.PlateFormSet(instance=self.object)
            context['cutting_forms'] = forms.CuttingFormSet(instance=self.object)
            context['edge_forms'] = forms.EdgeFormSet(instance=self.object)
            context['edging_forms'] = forms.EdgingFormSet(instance=self.object)
            context['others_forms'] = forms.OthersFormSet(instance=self.object)
            context['payment_forms'] = forms.PaymentFormSet(instance=self.object)
            context['add_note'] = forms.AddNoteForm

        context['current_plates'] = Plate.objects.filter(cutID=self.object)
        context['current_edges'] = Edge.objects.filter(cutID=self.object)
        context['current_payments'] = Payment.objects.filter(cutID=self.object)
        context['current_order'] = self.object

        return context

    def post(self, request, pk, *args, **kwargs):

        self.object = Order.objects.get(pk=pk)
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        add_note = forms.AddNoteForm(self.request.POST)
        note = self.request.POST['content']
        user = self.request.user.first_name

        all_tables = []

        PLATES = forms.PlateFormSet(self.request.POST, instance=self.object)
        all_tables.append(PLATES)
        CUTTING = forms.CuttingFormSet(self.request.POST, instance=self.object)
        all_tables.append(CUTTING)
        EDGES = forms.EdgeFormSet(self.request.POST, instance=self.object)
        all_tables.append(EDGES)
        EDGING = forms.EdgingFormSet(self.request.POST, instance=self.object)
        all_tables.append(EDGING)
        OTHER = forms.OthersFormSet(self.request.POST, instance=self.object)
        all_tables.append(OTHER)
        PAYMENTS = forms.PaymentFormSet(self.request.POST, instance=self.object)
        all_tables.append(PAYMENTS)

        if form.is_valid() and PLATES.is_valid() and EDGES.is_valid() and PAYMENTS.is_valid() and CUTTING.is_valid() and EDGING.is_valid() and OTHER.is_valid():
            messages.success(request, 'SAVED SUCCESSFULLY')
            return self.form_valid(form, PLATES, EDGES, PAYMENTS, CUTTING, EDGING, OTHER, add_note, user, note)
        else:
            messages.error(request, 'INVALID FORM')

            for table in all_tables:

                for error in table.errors:
                    if error:
                        messages.error(request, error.as_text())

                for row in table:
                    for field in row.fields:
                        if row.has_error(field, code=None):

                            if field in ['price']:
                                row.fields[field].widget.attrs = {
                                'class': 'form-control form-control-sm is-invalid', 
                                'step': '0.01',
                                'style': 'width: 90px',
                                }

                            elif field in ['quantity']:
                                row.fields[field].widget.attrs = {
                                'class': 'form-control form-control-sm is-invalid',
                                'style': 'width: 75px',
                                }

                            elif field in ['cutting_type', 'edging_type', 'description']:
                                row.fields[field].widget.attrs = {
                                'class': 'form-control form-control-sm is-invalid',
                                'style': 'width: 200px',
                                }

                            elif field in ['material']:
                                row.fields[field].widget.attrs = {
                                'class': 'form-control form-control-sm is-invalid',
                                'style': 'width: 170px',
                                }

                            else:
                                row.fields[field].widget.attrs = {
                                'class': 'form-control form-control-sm is-invalid',
                                'style': 'width: 100px',
                                }

            return self.form_invalid(form, PLATES, EDGES, PAYMENTS, CUTTING, EDGING, OTHER, user, add_note)

    def form_valid(self, form, PLATES, EDGES, PAYMENTS, CUTTING, EDGING, OTHER, add_note, user, note):

        self.object = form.save(commit=False)
        self.object.save()

        notes = add_note.save(commit=False)
        notes.user = user
        notes.cutID = self.object
        notes.content = note

        if note != '':
            notes.save()

            Change.objects.create(
            cutID=self.object,
            user=user, 
            operation='created', 
            what='Note',
            new_state=note,
            ).save()

        plate = PLATES.save(commit=False)

        for item in plate:

            if item.pk:

                old_object = Plate.objects.get(pk=item.pk)
                changed_fields = {}

                if old_object.material != item.material:
                    changed_fields['material'] = f'{old_object.material} -> {item.material}'

                if old_object.manufacturer != item.manufacturer:
                    changed_fields['manufacturer'] = f'{old_object.manufacturer} -> {item.manufacturer}'

                if old_object.quantity != item.quantity:
                    changed_fields['quantity'] = f'{old_object.quantity} -> {item.quantity}'

                if old_object.price != item.price:
                    changed_fields['price'] = f'{old_object.price} -> {item.price}'

                if old_object.from_client != item.from_client:
                    changed_fields['from_client'] = f'{old_object.from_client} -> {item.from_client}'

                for changed_field in changed_fields.keys():
                    Change.objects.create(
                    cutID=self.object,
                    user=user, 
                    operation='Changed', 
                    what=changed_field,
                    current_state=item.material,
                    new_state=changed_fields[changed_field],
                    ).save()
            else:
                Change.objects.create(
                cutID=self.object,
                user=user, 
                operation='Added', 
                what='Plate',
                new_state=item.material,
                ).save()

            item.cutID = self.object
            item.value = round((item.quantity * item.price), 2)
            item.save()

        for item in PLATES.deleted_objects:
            item.delete()

            Change.objects.create(
            cutID=self.object,
            user=user, 
            operation='Deleted', 
            what='Plate',
            new_state=item.material,
            ).save()

        cutting = CUTTING.save(commit=False)

        for item in cutting:

            if item.pk:

                old_object = Cutting.objects.get(pk=item.pk)
                changed_fields = {}

                if old_object.cutting_type != item.cutting_type:
                    changed_fields['cutting_type'] = f'{old_object.cutting_type} -> {item.cutting_type}'

                if old_object.quantity != item.quantity:

Tracking Table/table/templates/table/editOrder.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
{% load static %}

<div class="container">

	{% if messages %}
		{% for message in messages %}
			{% if message.tags == 'success' %}
				<div class="alert alert-success alert-dismissible fade show alertmsg" role="alert">
	  				<strong><div style="text-align: center;">{{ message }}</div></strong>
	  				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			{% else %}
				<div class="alert alert-danger alert-dismissible fade show alertmsg" role="alert">
	  				<strong><div style="text-align: center;">{{ message }}</div></strong>
	  				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			{% endif %}
		{% endfor %}
	{% endif %}	

	<div style="text-align: center; margin: 20px;">
		<h1>Edit Order</h1>
	</div>

<!-- 	<label class="form-label" for="OrderID">ID</label>
	<input type="text" id="OrderID" class="form-control" readonly value="{{current_order.ID}}">
	<br> -->

	<form method="POST" id="editOrderForm">
		{% csrf_token %}
															<!-- CLIENT INFO -->
		<label class="form-label" for="OrderID">ID</label>
		<input type="text" id="OrderID" class="form-control" readonly value="{{current_order.ID}}">
		<br>

		{% bootstrap_form form bound_css_class='' %}
		{% bootstrap_form add_note bound_css_class=''%}

															<!-- CLIENT INFO END -->

		{{plate_forms.management_form}}
		{{cutting_forms.management_form}}
		{{edge_forms.management_form}}
		{{edging_forms.management_form}}
		{{others_forms.management_form}}
		{{payment_forms.management_form}}

		<div class="row"> 										<!-- ROW 1 -->
			<div class="col"> 											<!-- PLATES TABLE -->
				<h4>Плочи</h4>
				<table class="table table-sm">
					<thead>
						<tr>
							<th>Материал</th>
							<th>Производител</th>
							<th>От клиент</th>
							<th>Количество</th>
							<th>Цена за брой</th>
							<th>Стойност</th>
							<th>
								<div style="text-align: center">
									<img src="{% static 'images/delete-can.png' %}" class="EditOrderIcons">
								</div>
							</th>
						</tr>
					</thead>
					<tbody>
						{% for item in plate_forms %}
							{{ item.id }}
							<tr>
								<td>{{item.material}}</td>
								<td>{{item.manufacturer}}</td>
								<td>
									<div class="form-check form-switch" style="margin-left: 19px; margin-top: 5px;">
										{{item.from_client}}
									</div>
								</td>
								<td>{{item.quantity}}</td>
								<td>{{item.price}}</td>
								<td>{{item.value}}</td>
								<td>
									<div class="form-check form-switch" style="margin-left: 10px; margin-top: 5px;">
										{{item.DELETE}}
									</div>
								</td>
							</tr>
						{% endfor %}
						<tr>
							<th colspan="5">All</th>
							<th>
								<div>
									{{current_order.plates_total}}
								</div>
							</th>
						</tr>
					</tbody>
				</table>
				
			</div>
			<div class="col"> 											<!-- CUTTING TABLE -->
				<h4>Рязане</h4>
				<table class="table table-sm">
					<thead>
						<tr>
							<th>Вид</th>
							<th>Количество</th>
							<th>Цена за брой</th>
							<th>Стоиност</th>
							<th>
								<div style="text-align: center">
									<img src="{% static 'images/delete-can.png' %}" class="EditOrderIcons">
								</div>
							</th>
						</tr>
					</thead>
					<tbody>
						{% for item in cutting_forms %}
							{{ item.id }}
							<tr>
								<td>{{item.cutting_type}}</td>
								<td>{{item.quantity}}</td>
								<td>{{item.price}}</td>
								<td>{{item.value}}</td>
								<td>
									<div class="form-check form-switch" style="margin-left: 10px; margin-top: 5px;">
										{{item.DELETE}}
									</div>
								</td>
							</tr>
						{% endfor %}
						<tr>
							<th colspan="3">All</th>
							<th>
								<div>
									{{current_order.cutting_total}}
								</div>
							</th>
						</tr>
					</tbody>
					
				</table>
			</div>
		</div>

		<div class="row"> 										<!-- ROW 2 -->
			<div class="col"> 											<!-- EDGES TABLE -->

				<h4>Кант</h4>
				<table class="table table-sm">
					<thead>
						<tr>
							<th>Вид</th>
							<th>Цвят</th>
							<th>Количество</th>
							<th>Цена за л.м.</th>
							<th>Стойност</th>
							<th>
								<div style="text-align: center">
									<img src="{% static 'images/eye2.png' %}" class="EditOrderIcons">
								</div>
							</th>
							<th>
								<div style="text-align: center">
									<img src="{% static 'images/delete-can.png' %}" class="EditOrderIcons">
								</div>
							</th>
						</tr>
					</thead>
					<tbody>
						{% for item in edge_forms %}
						{{ item.id }}
							<tr>
								<td>{{item.edge_type}}</td>
								<td>{{item.color_code}}</td>
								<td>{{item.quantity}}</td>
								<td>{{item.price}}</td>
								<td>{{item.value}}</td>
								<td>
									<div class="form-check form-switch" style="margin-left: 10px; margin-top: 5px;">
										{{item.visible}}
									</div>
								</td>
								<td>
									<div class="form-check form-switch" style="margin-left: 10px; margin-top: 5px;">
										{{item.DELETE}}
									</div>
								</td>
							</tr>
						{% endfor %}
						<tr>
							<th colspan="4">All</th>
							<th>
								<div>
									{{current_order.edge_total}}
								</div>
							</th>
						</tr>
					</tbody>
				</table>

			</div>
			<div class="col"> 											<!-- EDGING TABLE -->
				<h4>Кантиране</h4>
				<table class="table table-sm">
					<thead>
						<tr>
							<th>Вид</th>
							<th>Количество</th>
							<th>Цена за л.м.</th>
							<th>Стойност</th>
							<th>
								<div style="text-align: center">
									<img src="{% static 'images/delete-can.png' %}" class="EditOrderIcons">
								</div>
							</th>
						</tr>
					</thead>
					<tbody>
						{% for item in edging_forms %}
							{{ item.id }}
							<tr>
								<td>{{item.edging_type}}</td>
								<td>{{item.quantity}}</td>
								<td>{{item.price}}</td>
								<td>{{item.value}}</td>
								<td>
									<div class="form-check form-switch" style="margin-left: 10px; margin-top: 5px;">
										{{item.DELETE}}
									</div>
								</td>
							</tr>
						{% endfor %}
						<tr>
							<th colspan="3">All</th>
							<th>
								<div>
									{{current_order.edging_total}}
								</div>
							</th>
						</tr>
					</tbody>
					
				</table>
				
			</div>
			
		</div>

		<div class="row"> 										<!-- ROW 3 -->
			<div class="col"> 											<!-- OTHER TABLE -->
				<h4>Други услуги</h4>
				<table class="table">
					<thead>
						<tr>
							<th>Вид</th>
							<th>Количество</th>
							<th>Единична цена</th>
							<th>Стойност</th>
							<th>
								<div style="text-align: center">
									<img src="{% static 'images/delete-can.png' %}" class="EditOrderIcons">
								</div>
							</th>
						</tr>
					</thead>
					<tbody>
						{% for item in others_forms %}
						{{ item.id }}
							<tr>
								<td>{{item.description}}</td>
								<td>{{item.quantity}}</td>
								<td>{{item.price}}</td>
								<td>{{item.value}}</td>
								<td>
									<div class="form-check form-switch" style="margin-left: 10px; margin-top: 5px;">
										{{item.DELETE}}
									</div>
								</td>
							</tr>
						{% endfor %}
						<tr>
							<th colspan="3">All</th>
							<th>
								<div>
									{{current_order.others_total}}
								</div>
							</th>
						</tr>
					</tbody>
					
				</table>
			</div>
			<div class="col"> 											<!-- PAYMENT TABLE -->
				<h4>Плащания</h4>
				<br>
				<table class="table table-sm">
					<tbody>
						<tr>
							<td><strong>TOTAL VALUE</strong></td>
							<td><strong>{{current_order.total_price}}</strong></td>
						</tr>
						{% for item in payment_forms %}
							{{ item.id }}
							<tr>
								<td>PAID</td>
								<td>{{item.payment_method}}</td>
								<td>{{item.value}}</td>
							</tr>
						{% endfor %}
						<tr>
							<td scope="3"><strong>All</strong></td>
							<td></td>
							<td><strong>{{current_order.paid}}</strong></td>
						</tr>
						<tr>
							<td><strong>LEFT</strong></td>
							<td><strong>{{current_order.balance}}</strong></td>
						</tr>
					</tbody>
					
				</table>
			</div>
			
		</div>
		<br><br><br>

		<div style="margin-left: 48%; margin-right: 50%; padding-bottom: 20px;">
			<a class="btn btn-outline-info" href="{% url 'table:printOrder' pk=current_order %}" role="button" target="_blank" title="Print View">
				<img src="{% static 'images/printer.png' %}" class="tableIcons">
			</a>
		</div>

		<div class="d-grid gap-2 col-3 mx-auto">
			<!-- <input type="submit" class="btn btn-primary" value="Update" id="editButton"> -->
			<button type="submit" class="btn btn-primary" id="editButton">Update</button>
		</div>
	</form>
	
</div>

{% endblock %}

Tracking Table/table/templates/table/newOrder.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

<div class="container">

	<div style="text-align: center; margin: 20px;">
		<h1>Create Order</h1>
	</div>

	<form method="POST">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% bootstrap_form add_note %}
		<input type="submit" class="btn btn-primary" value="Create">
	</form>
	
</div>

{% endblock %}

Tracking Table/table/templates/table/printOrder.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>TTable Print View</title>
	<link rel="icon" type="image/x-icon" href="{% static 'images/printer.png' %}">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</head>
<body>


	<div class="container" style="padding-top: 20px;">

		<table class="table table-sm table-bordered border-dark">

			<thead>
				<tr>
					<th scope="col" rowspan="3" 
					style="text-align: left; ">
						МЕГА ТРЕЙДИНГ ЕООД <br>
						магазин "Всичко за мебелиста" <br>
						Магазин: гр.София, ж.к. Модерно Предградие <br>
						ул. Адам Мицкевич (на ъгъла с ул. 3019) <br>
						Склад: гр. София, ул. Илиянско шосе 8А  <br>
						Тел: 0895 75 03 75; 0893 45 70 87 <br>
						e-mail: razkroi_mt@abv.bg; www.megatrading.bg
					</th>
					<th scope="col">
						Поръчка № {{order.ID}} <br>   
						Дата: {{order.created_date|date:'d.m.Y'}}
					</th>
				</tr>
				<tr>
					<th>Клиент: {{order.owner}}</th>
				</tr>
				<tr>
					<th>Тел: {{order.telephone}}</th>
				</tr>
			</thead>

		</table>

	</div>
	<div class="container" style="padding-top: 10px">
		<div class="row">
			<div class="col">

				<table class="table table-sm table-bordered border-dark">
					<thead>
						<tr>
							<th scope="col">Материал</th>
							<th scope="col">Брой</th>
							<th scope="col">Ед. цена</th>
							<th scope="col">Ст-ст</th>
						</tr>
					</thead>
					<tbody>
						{% for plate in order_plates %}
							<tr>
								<td>{{plate.material}}</td>
								<td>{{plate.quantity}}</td>
								<td>{{plate.price}}</td>
								<td>{{plate.value}}</td>
							</tr>
						{% endfor %}
						<th colspan="3">Обща стойност</th>
						<th>{{order.plates_total}}</th>
					</tbody>
				</table>
				
			</div>

			<div class="col">
				<table class="table table-sm table-bordered border-dark">
					<thead>
						<tr>
							<th scope="col">Разкрояване</th>
							<th scope="col">Брой</th>
							<th scope="col">Ед. цена</th>
							<th scope="col">Ст-ст</th>
						</tr>
					</thead>
					<tbody>
						{% for cut in order_cutting %}
							<tr>
								<td>{{cut.cutting_type}}</td>
								<td>{{cut.quantity}}</td>
								<td>{{cut.price}}</td>
								<td>{{cut.value}}</td>
							</tr>
						{% endfor %}
						<th colspan="3">Обща стойност</th>
						<th>{{order.cutting_total}}</th>
					</tbody>
				</table>
				
			</div>
			
		</div>
		<div class="row">
			<div class="col">
				<table class="table table-sm table-bordered border-dark">
					<thead>
						<tr>
							<th scope="col">Кант</th>
							<th scope="col">Цвят</th>
							<th scope="col">л.м.</th>
							<th scope="col">Ед. цена</th>
							<th scope="col">Ст-ст</th>
						</tr>
					</thead>
					<tbody>
						{% for edge in order_edges %}
							<tr>
								<td>{{edge.edge_type}}</td>
								<td>{{edge.color_code}}</td>
								<td>{{edge.quantity}}</td>
								<td>{{edge.price}}</td>
								<td>{{edge.value}}</td>
							</tr>
						{% endfor %}
						<th colspan="4">Обща стойност</th>
						<th>{{order.edge_total}}</th>
					</tbody>
				</table>

				
			</div>
			<div class="col">
				<table class="table table-sm table-bordered border-dark">
					<thead>
						<tr>
							<th scope="col">Кантиране</th>
							<th scope="col">л.м.</th>
							<th scope="col">Ед. цена</th>
							<th scope="col">Ст-ст</th>
						</tr>
					</thead>
					<tbody>
						{% for edging in order_edging %}
							<tr>
								<td>{{edging.edging_type}}</td>
								<td>{{edging.quantity}}</td>
								<td>{{edging.price}}</td>
								<td>{{edging.value}}</td>
							</tr>
						{% endfor %}
						<th colspan="3">Обща стойност</th>
						<th>{{order.edging_total}}</th>
					</tbody>
				</table>
				
			</div>
			
		</div>
		<div class="row">
			<div class="col">

				<table class="table table-sm table-bordered border-dark">
					<thead>
						<tr>
							<th scope="col">Други услуги</th>
							<th scope="col">Брой</th>
							<th scope="col">Ед. цена</th>
							<th scope="col">Ст-ст</th>
						</tr>
					</thead>
					<tbody>
						{% for other in order_others %}
							<tr>
								<td>{{other.description}}</td>
								<td>{{other.quantity}}</td>
								<td>{{other.price}}</td>
								<td>{{other.value}}</td>
							</tr>
						{% endfor %}
						<th colspan="3">Обща стойност</th>
						<th>{{order.others_total}}</th>
					</tbody>
				</table>

			</div>
			<div class="col">

				<table class="table table-sm table-bordered border-dark">
					<thead>
						<tr>
							<th scope="col" colspan="2">
								Обща стойност:
							</th>
								<th scope="col"><strong>{{order.total_price}}</strong></th>
						</tr>
					</thead>
					<tbody>
						{% for payment in order_payments %}
						<tr>
							<td>Авансово</td>
							<td>{{payment.payment_method}}</td>
							<td>{{payment.value}}</td>
						</tr>
						{% endfor %}
						<!-- <tr>
							<th colspan="3">{{order.paid}}</th>
							
						</tr> -->
						<tr>
							<th colspan="2">
								Остатък<br>
								за доплащане
							</th>
							<th>{{order.balance}}</th>
						</tr>
					</tbody>
				</table>
				
			</div>
			
		</div>
		
	</div>



</body>
</html>