Tracking Table/SimpleTable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from SimpleTable import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='internals/'), name='home'),
    path('internals/', views.Internals.as_view(), name='internals'),
    path('externals/', views.Externals.as_view(), name='externals'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('table/', include('table.urls', namespace='table')),
    path('internals/react/', views.react_response, name='react'),
]

Tracking Table/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('createUser/', views.CreateUser.as_view(), name='createUser'),
    path('viewUsers/', views.ViewUsers.as_view(), name='viewUsers'),
]

Tracking Table/table/urls.py
from django.urls import path
from table import views

app_name = 'table'

urlpatterns = [
    path('createOrder/', views.CreateOrder.as_view(), name='newOrder'),
    path('editOrder/<int:pk>/', views.EditOrder.as_view(), name='editOrder'),
    path('deleteOrder/<int:pk>', views.DeleteOrder.as_view(), name='deleteOrder'),
    path('updateOrder/<int:pk>', views.UpdateOrder.as_view(), name='updateOrder'),
    path('printOrder/<int:pk>', views.PrintOrder.as_view(), name='printOrder'),
    path('getOrderHistory/<int:pk>', views.GetOrderHistory.as_view(), name='orderHistory'),
]

Tracking Table/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>TTable</title>
	<link rel="icon" type="image/x-icon" href="{% static 'images/favico.png' %}">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@700&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/progressbar.css' %}">

</head>
<body>

	<nav class="navbar navbar-expand-sm navbar-light" style="background-color: #e6e6e9; --bs-bg-opacity: .5;">
		<div class="container-fluid">

			<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/favico.png' %}" style="width: 30px; height: 30px; margin-bottom: 2px;"></a>

	      	<ul class="navbar-nav me-auto mb-2 mb-lg-0">

		        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><img src="{% static 'images/user-group.png' %}" style="width: 28px; height: 28px;"></a>
		          	<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
			            <li><a class="dropdown-item" href="{% url 'accounts:viewUsers' %}">Manage Users</a></li>
			            <li><hr class="dropdown-divider"></li>
			            <li><a class="dropdown-item" href="{% url 'accounts:createUser' %}">Create User</a></li>
			            <li><a class="dropdown-item" href="#">Delete User</a></li>
		          	</ul>
		        </li>

	      	</ul>

			<span class="navbar-text">
			    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

			        <li class="nav-item dropdown">
			        	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Welcome <strong>{{user.first_name}}</strong> <img src="{% static 'images/user.png' %}" class="navbarIcons"></a>
			          	<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
				            <li><a class="dropdown-item" href="#">View Profile</a></li>
				            <li><hr class="dropdown-divider"></li>
				            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
			          	</ul>
			        </li>

		      	</ul>
	      	</span>
	    	
	  	</div>
	</nav>

	{% block content %}
	{% endblock %}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/history.js' %}"></script>

	<br>
	<div class="sticky-bottom">
		
		<div class="container WebFooter" style="text-align: center;">
			<p>Megatrading Ltd© 2022</p>
		</div>
	</div>
	<br>

</body>
</html>